// PortalChat.jsx — conversational lead-prequal flow with LIVE AI.
//
// The flow is still structured (we need specific data points for
// routing), but Ivy's greetings, acknowledgments, transitions, and
// off-topic replies are generated by window.claude.complete so it
// feels like a human. When the user types something conversational,
// Ivy responds in-character before nudging back toward the next
// structured input.

const { useState, useEffect, useRef, useMemo } = React;

// ─────────────────────────────────────────────────────────────
// Conversation script — each step defines:
//   - `ask`: the thing Ivy needs to learn in this step
//   - `input`: what surface the user completes it on
//   - `topic`: passed to the LLM so it knows what to ask / riff on
// ─────────────────────────────────────────────────────────────
const SCRIPT = [
  { id: 'greet', ask: 'Greet the lead, introduce yourself (Ivy, project coordinator at Moss & Stone), reference what they originally inquired about, and ask if they have a few minutes for a quick chat to help route them to the right designer.',
    input: { kind: 'chips', options: ['Sounds good', 'Only have a minute', 'Can we do this later?'], commitAs: 'consent' } },
  { id: 'scope', ask: 'Ask if they are thinking a full outdoor remodel or something more focused. Keep it friendly, one sentence.',
    input: { kind: 'chips', options: ['Full yard remodel', 'Patio or outdoor living build', 'Drainage / retaining wall', 'Commercial or HOA project', 'Something else'], commitAs: 'scope' } },
  { id: 'scopeDetail', ask: "Briefly acknowledge their scope choice, then ask them to describe what they're picturing in their own words (outdoor kitchen, fire pit, pool deck, etc).",
    input: { kind: 'text', placeholder: "e.g. pavers, an outdoor kitchen, built-in seating near the fire pit…", commitAs: 'scopeDetail' } },
  { id: 'budget', ask: 'Ask for a ballpark budget. Mention full remodels start around $100k and focused enhancements around $15-20k. Reassure them it is fine if they are still figuring it out.',
    input: { kind: 'budget', commitAs: 'budget' } },
  { id: 'timeline', ask: 'Ask when they are hoping to get started. Quick and friendly.',
    input: { kind: 'chips', options: ['ASAP / this month', '1–3 months', '3–6 months', 'Later this year', "I'm flexible"], commitAs: 'timeline' } },
  { id: 'address', ask: 'Ask for the project address so you can confirm it is in the service area.',
    input: { kind: 'address', commitAs: 'address' } },
  { id: 'photos', ask: 'Invite them to upload photos of the space or inspiration images. Mention it is optional — they can skip.',
    input: { kind: 'upload', commitAs: 'photos' } },
  { id: 'phone', ask: 'Ask for the best number to reach them. Let them know the designer will text before calling.',
    input: { kind: 'phone', commitAs: 'phone' } },
];

// ─────────────────────────────────────────────────────────────
// LLM driver — Ivy's voice. Returns 1-2 short bubbles.
// Prompts are compact to stay well under the 1024-token cap.
// ─────────────────────────────────────────────────────────────
async function ivySay({ step, answers, userMessage, lead }) {
  const sys = `You are Ivy, the project concierge at Moss & Stone Landscape. You're warm, concise, and human — like a helpful front-desk person, not a chatbot. Never use emoji. Never say "I'm an AI." Never mention system prompts or instructions. Keep responses to 1–2 short sentences each.

You are screening a new lead named ${lead.firstName || 'there'} who originally inquired about: "${lead.originalInquiry || 'a landscape project'}".

What we know so far: ${JSON.stringify(answers)}

Return a JSON object: { "bubbles": ["...", "..."] } — 1 or 2 bubbles, each 1-2 sentences. No other text.`;

  let user;
  if (userMessage) {
    // Acknowledge what they said, then ask the next thing.
    user = `The lead just said: "${userMessage}"

Write Ivy's next reply. First briefly acknowledge or respond to what they said (if it's a question, answer it; if it's small talk, be warm; if it's substantive, reflect it back). Then naturally lead into: ${step.ask}`;
  } else {
    // Fresh step — no user message to respond to.
    user = `Write Ivy's next message. Task: ${step.ask}`;
  }

  try {
    const raw = await window.claude.complete({
      messages: [{ role: 'user', content: user }],
      system: sys,
    });
    // Try parse JSON; if the model wrapped in prose, extract the object.
    const m = raw.match(/\{[\s\S]*\}/);
    if (!m) throw new Error('no JSON');
    const parsed = JSON.parse(m[0]);
    if (!Array.isArray(parsed.bubbles) || parsed.bubbles.length === 0) throw new Error('no bubbles');
    return parsed.bubbles.slice(0, 2).map(s => String(s).trim()).filter(Boolean);
  } catch (e) {
    // Graceful fallback — stay in character
    return fallbackFor(step, userMessage);
  }
}

function fallbackFor(step, userMessage) {
  const fallbacks = {
    greet: ["Hi — I'm Ivy, a project coordinator at Moss & Stone.", "Mind if I ask a few quick things so I can get you to the right designer?"],
    scope: ["First — are you thinking a full outdoor remodel, or something more focused?"],
    scopeDetail: ["Nice. Tell me a little about what you're picturing — whatever's on your mind."],
    budget: ["Do you have a ballpark budget in mind? Fine if you're still figuring it out."],
    timeline: ["When are you hoping to get started?"],
    address: ["What's the project address? I'll confirm it's in our service area."],
    photos: ["If you have photos of the space or inspiration, drop them here. Totally optional."],
    phone: ["Last thing — what's the best number to reach you?"],
  };
  const ack = userMessage ? ["Got it."] : [];
  return [...ack, ...(fallbacks[step.id] || ["Let's keep going."])];
}

// Generate a warm closing message once all answers are in.
async function ivyClose({ answers, routing, lead }) {
  const sys = `You are Ivy, project concierge at Moss & Stone. Warm, concise. No emoji.`;
  const user = `The lead (${lead.firstName}) just finished answering everything. Here's the data:
${JSON.stringify(answers, null, 2)}

They will be routed to: ${routing.owner} (${routing.team}).

Write a SHORT warm wrap-up message — 1 sentence acknowledging they're all set, mentioning who will reach out (${routing.owner}) and that they'll text before calling. Reply with JSON: { "bubbles": ["..."] }`;
  try {
    const raw = await window.claude.complete({ messages: [{ role: 'user', content: user }], system: sys });
    const m = raw.match(/\{[\s\S]*\}/);
    const parsed = JSON.parse(m[0]);
    return parsed.bubbles.slice(0, 1);
  } catch {
    return [`Perfect — you're all set. ${routing.owner} will text you before calling.`];
  }
}

// ─────────────────────────────────────────────────────────────
// Routing engine — applies cheat-sheet logic to collected answers
// ─────────────────────────────────────────────────────────────
function computeRouting(answers) {
  const scope = (answers.scope || '').toLowerCase();
  const detail = (answers.scopeDetail || '').toLowerCase();
  const budgetRaw = answers.budget && answers.budget.raw;
  const budgetLabel = (answers.budget && answers.budget.label) || '';

  // DQ checks
  const dqKeywords = ['tree trim', 'tree remov', 'just mow', 'lawn mow', 'junk removal', 'cleanup only', 'one-off', 'small repair'];
  if (dqKeywords.some(k => detail.includes(k))) {
    return { team: 'DQ', owner: 'Sales review', confidence: 88, reason: 'Out-of-scope single trade' };
  }
  if (budgetRaw !== null && budgetRaw !== undefined && budgetRaw < 15) {
    return { team: 'DQ', owner: 'Sales review', confidence: 82, reason: 'Budget below $15k minimum' };
  }

  // Commercial
  if (scope.includes('commercial') || scope.includes('hoa') || detail.includes('hoa') || detail.includes('commercial')) {
    if (detail.includes('maintenance') || detail.includes('weekly') || detail.includes('mowing')) {
      return { team: 'Biz Dev', owner: 'Jamie Reyes', confidence: 93, reason: 'Commercial/HOA maintenance contract' };
    }
    return { team: 'Commercial', owner: 'Brian Wallace', confidence: 89, reason: 'Commercial build — confirm non-union' };
  }

  // Res lite
  if (scope.includes('drainage') || scope.includes('retaining')) {
    return { team: 'Res Lite', owner: 'Kendel Okafor', confidence: 90, reason: 'Focused enhancement scope' };
  }
  if (budgetRaw !== null && budgetRaw < 50) {
    return { team: 'Res Lite', owner: 'Kendel Okafor', confidence: 85, reason: 'Sub-$50k enhancement' };
  }

  // Design-Build default
  if (budgetRaw >= 100) {
    return { team: 'Design-Build', owner: 'Rudy Alvarez', confidence: 94, reason: 'Large remodel, full scope' };
  }
  return { team: 'Design-Build', owner: 'Megha Iyer', confidence: 87, reason: 'Design-build remodel' };
}

// ─────────────────────────────────────────────────────────────
// Bubble
// ─────────────────────────────────────────────────────────────
function Bubble({ children, role = 'ai' }) {
  const isAI = role === 'ai';
  return (
    <div style={{
      display: 'flex', justifyContent: isAI ? 'flex-start' : 'flex-end',
      marginBottom: 8, animation: 'bubbleIn .35s cubic-bezier(.2,.7,.3,1)',
    }}>
      <div style={{
        maxWidth: '78%', padding: '11px 15px',
        background: isAI ? '#fff' : T.forest,
        color: isAI ? T.ink : T.cream,
        borderRadius: isAI ? '18px 18px 18px 4px' : '18px 18px 4px 18px',
        fontFamily: T.sans, fontSize: 15.5, lineHeight: 1.4,
        boxShadow: isAI ? '0 1px 2px rgba(42,36,29,.06)' : 'none',
        border: isAI ? `1px solid ${T.lineSoft}` : 'none',
        fontWeight: isAI ? 400 : 450, letterSpacing: -0.1,
        whiteSpace: 'pre-wrap', wordBreak: 'break-word',
      }}>{children}</div>
    </div>
  );
}

function TypingIndicator() {
  return (
    <div style={{ display: 'flex', justifyContent: 'flex-start', marginBottom: 8 }}>
      <div style={{
        padding: '14px 16px', background: '#fff', borderRadius: '18px 18px 18px 4px',
        border: `1px solid ${T.lineSoft}`, display: 'flex', gap: 4, alignItems: 'center',
      }}>
        {[0, 1, 2].map(i => (
          <span key={i} style={{
            width: 6, height: 6, borderRadius: 3, background: T.inkFaint,
            animation: `typingDot 1.3s ${i * 0.18}s infinite ease-in-out`,
          }}/>
        ))}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Input surfaces
// ─────────────────────────────────────────────────────────────
function Chips({ options, onPick }) {
  return (
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', padding: '12px 16px 14px',
      background: T.creamDeep, borderTop: `1px solid ${T.line}` }}>
      {options.map(o => (
        <button key={o} onClick={() => onPick(o)}
          style={{
            padding: '10px 16px', border: `1px solid ${T.forest}`, background: 'transparent',
            color: T.forest, borderRadius: 999, fontFamily: T.sans, fontSize: 14.5, fontWeight: 500,
            cursor: 'pointer', letterSpacing: -0.1, transition: 'all .15s',
          }}
          onMouseEnter={e => { e.currentTarget.style.background = T.forest; e.currentTarget.style.color = T.cream; }}
          onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.color = T.forest; }}
        >{o}</button>
      ))}
    </div>
  );
}

function BudgetInput({ onCommit }) {
  const [v, setV] = useState(75);
  const current = v >= 250 ? `$${v}k+` : `$${Math.max(5, v)}k`;
  const label = v < 20 ? 'Enhancement size' : v < 50 ? 'Small remodel' : v < 100 ? 'Partial yard' : v < 200 ? 'Full yard remodel' : 'Luxury build';
  return (
    <div style={{ padding: '18px 20px', background: T.creamDeep, borderTop: `1px solid ${T.line}` }}>
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 14 }}>
        <div>
          <div style={{ fontFamily: T.display, fontSize: 32, fontWeight: 500, color: T.forest, letterSpacing: -1, lineHeight: 1 }}>{current}</div>
          <div style={{ fontFamily: T.sans, fontSize: 13, color: T.inkSoft, marginTop: 4 }}>{label}</div>
        </div>
        <button onClick={() => onCommit({ label: current, tier: label, raw: v })}
          style={{ padding: '10px 18px', background: T.forest, color: T.cream, border: 'none',
            borderRadius: 999, fontFamily: T.sans, fontSize: 14, fontWeight: 500, cursor: 'pointer' }}>
          Looks right →
        </button>
      </div>
      <input type="range" min={5} max={500} step={5} value={v} onChange={e => setV(+e.target.value)}
        style={{ width: '100%', accentColor: T.forest, height: 4 }} />
      <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8,
        fontFamily: T.mono, fontSize: 10.5, color: T.inkFaint, letterSpacing: 0.4, textTransform: 'uppercase' }}>
        <span>$5k</span><span>$50k</span><span>$100k</span><span>$250k</span><span>$500k+</span>
      </div>
      <button onClick={() => onCommit({ label: 'Not sure yet', tier: 'unsure', raw: null })}
        style={{ marginTop: 12, background: 'transparent', border: 'none', color: T.inkSoft,
          fontFamily: T.sans, fontSize: 13, cursor: 'pointer', textDecoration: 'underline',
          textUnderlineOffset: 3, textDecorationColor: T.stone }}>
        Not sure yet — skip this
      </button>
    </div>
  );
}

// ── Real OSM Nominatim address autocomplete ─────────────────
function AddressInput({ onCommit }) {
  const [addr, setAddr] = useState('');
  const [suggestions, setSuggestions] = useState([]);
  const [loading, setLoading] = useState(false);
  const abortRef = useRef(null);

  useEffect(() => {
    if (addr.length < 4) { setSuggestions([]); return; }
    if (abortRef.current) abortRef.current.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;
    const t = setTimeout(async () => {
      setLoading(true);
      try {
        const url = `https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&countrycodes=us&limit=5&q=${encodeURIComponent(addr)}`;
        const res = await fetch(url, { signal: ctrl.signal, headers: { 'Accept': 'application/json' } });
        const data = await res.json();
        setSuggestions(data.map(r => ({ display: r.display_name, lat: r.lat, lon: r.lon })));
      } catch (e) {
        if (e.name !== 'AbortError') setSuggestions([]);
      } finally { setLoading(false); }
    }, 300);
    return () => { clearTimeout(t); ctrl.abort(); };
  }, [addr]);

  return (
    <div style={{ padding: '14px 16px', background: T.creamDeep, borderTop: `1px solid ${T.line}` }}>
      <div style={{ position: 'relative' }}>
        <div style={{ position: 'absolute', left: 14, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }}>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke={T.inkFaint} strokeWidth="1.6">
            <path d="M8 14s5-4.5 5-8.5A5 5 0 008 1a5 5 0 00-5 4.5C3 9.5 8 14 8 14z"/><circle cx="8" cy="5.5" r="1.8"/>
          </svg>
        </div>
        <input value={addr} onChange={e => setAddr(e.target.value)}
          placeholder="Start typing the project address…"
          style={{ width: '100%', padding: '12px 44px 12px 38px', border: `1px solid ${T.line}`,
            background: '#fff', borderRadius: 10, fontFamily: T.sans, fontSize: 15, color: T.ink,
            outline: 'none', boxSizing: 'border-box' }}
          onFocus={e => e.target.style.borderColor = T.forest}
          onBlur={e => e.target.style.borderColor = T.line} />
        {addr.length > 0 && (
          <button onClick={() => onCommit({ address: addr })}
            style={{ position: 'absolute', right: 6, top: '50%', transform: 'translateY(-50%)',
              background: T.forest, color: T.cream, border: 'none', borderRadius: 8,
              width: 34, height: 34, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
              <path d="M2 7h10M8 3l4 4-4 4"/>
            </svg>
          </button>
        )}
      </div>
      {(suggestions.length > 0 || loading) && (
        <div style={{ marginTop: 8, background: '#fff', borderRadius: 10, border: `1px solid ${T.line}`, overflow: 'hidden' }}>
          {loading && (
            <div style={{ padding: '10px 14px', fontFamily: T.mono, fontSize: 11, color: T.inkFaint, letterSpacing: 0.4 }}>
              Searching…
            </div>
          )}
          {suggestions.map((s, i) => (
            <button key={i} onClick={() => onCommit({ address: s.display, lat: s.lat, lon: s.lon })}
              style={{ display: 'flex', width: '100%', padding: '10px 14px', background: 'transparent',
                border: 'none', borderBottom: i < suggestions.length - 1 ? `1px solid ${T.lineSoft}` : 'none',
                cursor: 'pointer', textAlign: 'left', gap: 10, alignItems: 'flex-start',
                fontFamily: T.sans, fontSize: 13, color: T.ink, lineHeight: 1.4 }}>
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke={T.inkFaint} strokeWidth="1.5" style={{ marginTop: 2, flexShrink: 0 }}>
                <path d="M7 12s4-3.5 4-7A4 4 0 007 1a4 4 0 00-4 4C3 8.5 7 12 7 12z"/>
              </svg>
              <span style={{ textAlign: 'left' }}>{s.display}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Real file upload with thumbnail previews ────────────────
function UploadInput({ onCommit }) {
  const [files, setFiles] = useState([]);
  const photoRef = useRef(null);
  const docRef = useRef(null);

  const addFiles = (fileList) => {
    const arr = Array.from(fileList).map(f => {
      const isImage = f.type.startsWith('image/');
      return {
        name: f.name, size: f.size, type: f.type,
        kind: isImage ? 'photo' : 'doc',
        url: isImage ? URL.createObjectURL(f) : null,
      };
    });
    setFiles(f => [...f, ...arr]);
  };

  const removeAt = (idx) => setFiles(f => f.filter((_, i) => i !== idx));

  const fmtSize = (n) => n < 1024 ? `${n}b` : n < 1024*1024 ? `${Math.round(n/1024)}kb` : `${(n/1024/1024).toFixed(1)}mb`;

  return (
    <div style={{ padding: '14px 16px', background: T.creamDeep, borderTop: `1px solid ${T.line}` }}>
      {files.length > 0 && (
        <div style={{ display: 'flex', gap: 8, marginBottom: 12, flexWrap: 'wrap' }}>
          {files.map((f, i) => (
            <div key={i} style={{ position: 'relative', width: 64, height: 64, borderRadius: 10,
              background: f.url ? `url(${f.url}) center/cover` : T.cream,
              border: f.url ? 'none' : `1px dashed ${T.stone}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontFamily: T.mono, fontSize: 9, color: T.inkSoft, textAlign: 'center', padding: 4,
              overflow: 'hidden' }}>
              {!f.url && (
                <div style={{ textTransform: 'uppercase', letterSpacing: 0.5 }}>
                  {(f.name.split('.').pop() || 'doc').slice(0,4)}
                </div>
              )}
              <button onClick={() => removeAt(i)}
                style={{ position: 'absolute', top: 2, right: 2, width: 18, height: 18,
                  borderRadius: 9, background: 'rgba(0,0,0,.55)', color: '#fff', border: 'none',
                  cursor: 'pointer', fontSize: 11, lineHeight: 1, padding: 0 }}>×</button>
            </div>
          ))}
        </div>
      )}
      <input ref={photoRef} type="file" accept="image/*" multiple style={{ display: 'none' }}
        onChange={e => addFiles(e.target.files)} />
      <input ref={docRef} type="file" accept=".pdf,.doc,.docx,image/*" multiple style={{ display: 'none' }}
        onChange={e => addFiles(e.target.files)} />
      <div style={{ display: 'flex', gap: 8 }}>
        <button onClick={() => photoRef.current?.click()}
          style={{ flex: 1, padding: '12px', background: '#fff', border: `1px solid ${T.line}`,
            borderRadius: 10, fontFamily: T.sans, fontSize: 13.5, color: T.ink, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, fontWeight: 500 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke={T.forest} strokeWidth="1.6">
            <rect x="1.5" y="3" width="13" height="10" rx="1.5"/><circle cx="6" cy="7.5" r="1.2"/>
            <path d="M2 12l3.5-3.5L9 11l2-2 3 3"/>
          </svg>
          Add photos
        </button>
        <button onClick={() => docRef.current?.click()}
          style={{ flex: 1, padding: '12px', background: '#fff', border: `1px solid ${T.line}`,
            borderRadius: 10, fontFamily: T.sans, fontSize: 13.5, color: T.ink, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, fontWeight: 500 }}>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke={T.forest} strokeWidth="1.6">
            <path d="M3 1.5h6l3.5 3.5V14a.5.5 0 01-.5.5H3a.5.5 0 01-.5-.5V2a.5.5 0 01.5-.5z"/>
            <path d="M9 1.5V5h3.5"/>
          </svg>
          Plans / docs
        </button>
      </div>
      <div style={{ display: 'flex', gap: 12, marginTop: 12, alignItems: 'center', justifyContent: 'space-between' }}>
        <button onClick={() => onCommit({ files: [], skipped: true })}
          style={{ background: 'transparent', border: 'none', color: T.inkSoft, fontFamily: T.sans,
            fontSize: 13, cursor: 'pointer', textDecoration: 'underline', textUnderlineOffset: 3,
            textDecorationColor: T.stone, padding: 0 }}>
          Skip — no photos
        </button>
        {files.length > 0 && (
          <button onClick={() => onCommit({ files, skipped: false })}
            style={{ padding: '9px 16px', background: T.forest, color: T.cream, border: 'none',
              borderRadius: 999, fontFamily: T.sans, fontSize: 13.5, fontWeight: 500, cursor: 'pointer' }}>
            Send {files.length} {files.length === 1 ? 'file' : 'files'} →
          </button>
        )}
      </div>
    </div>
  );
}

function TextInput({ placeholder, onCommit, kind = 'text', autofocus = false }) {
  const [v, setV] = useState('');
  const ref = useRef(null);
  useEffect(() => { if (autofocus && ref.current) ref.current.focus(); }, [autofocus]);
  const submit = () => { if (v.trim()) { onCommit(v.trim()); setV(''); } };
  return (
    <div style={{ padding: '12px 16px 14px', background: T.creamDeep, borderTop: `1px solid ${T.line}` }}>
      <div style={{ position: 'relative' }}>
        <textarea ref={ref} value={v} onChange={e => setV(e.target.value)} placeholder={placeholder}
          rows={kind === 'phone' ? 1 : 2} inputMode={kind === 'phone' ? 'tel' : 'text'}
          onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); submit(); } }}
          style={{ width: '100%', padding: '12px 48px 12px 14px', border: `1px solid ${T.line}`,
            background: '#fff', borderRadius: 14, fontFamily: T.sans, fontSize: 15,
            color: T.ink, outline: 'none', resize: 'none', boxSizing: 'border-box', lineHeight: 1.4 }}
          onFocus={e => e.target.style.borderColor = T.forest}
          onBlur={e => e.target.style.borderColor = T.line}/>
        <button onClick={submit} disabled={!v.trim()}
          style={{ position: 'absolute', right: 6, bottom: 6,
            background: v.trim() ? T.forest : T.stone, color: T.cream, border: 'none', borderRadius: 10,
            width: 34, height: 34, cursor: v.trim() ? 'pointer' : 'default', display: 'flex',
            alignItems: 'center', justifyContent: 'center', transition: 'background .15s' }}>
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
            <path d="M7 12V2M3 6l4-4 4 4"/>
          </svg>
        </button>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Summary screen
// ─────────────────────────────────────────────────────────────
function SummaryScreen({ answers, onEdit, lead, routing, compact = false }) {
  const photoCount = answers.photos && answers.photos.files ? answers.photos.files.length : 0;
  const rows = [
    { k: 'Project scope', v: answers.scope || '—' },
    { k: "What you're picturing", v: answers.scopeDetail || '—' },
    { k: 'Budget', v: (answers.budget && answers.budget.label) || '—' },
    { k: 'Timeline', v: answers.timeline || '—' },
    { k: 'Address', v: (answers.address && answers.address.address) || '—' },
    { k: 'Photos & plans', v: photoCount > 0 ? `${photoCount} attached` : 'None' },
    { k: 'Phone', v: answers.phone || '—' },
  ];
  return (
    <div style={{ padding: compact ? '20px 20px 32px' : '28px 28px 40px', background: T.cream, minHeight: '100%' }}>
      <div style={{ width: 44, height: 44, borderRadius: 22, background: T.forest,
        display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 14 }}>
        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke={T.cream} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M4 10l4 4 8-8"/>
        </svg>
      </div>
      <h1 style={{ fontFamily: T.display, fontSize: compact ? 30 : 38, fontWeight: 400,
        color: T.forestDeep, letterSpacing: -1, margin: 0, lineHeight: 1.05 }}>
        Thanks, <em style={{ fontStyle: 'italic', color: T.terracotta }}>{(lead && lead.firstName) || 'there'}</em>.
        <br/>We've got what we need.
      </h1>
      <p style={{ fontFamily: T.sans, fontSize: 15, color: T.inkSoft, margin: '12px 0 24px', lineHeight: 1.5, maxWidth: 380 }}>
        Your project is headed to <strong style={{ color: T.ink, fontWeight: 500 }}>{routing.owner}</strong>
        {routing.team !== 'DQ' && <> on our <strong style={{ color: T.ink, fontWeight: 500 }}>{routing.team}</strong> team</>}
        . They'll reach out within one business day to set up a site walk.
      </p>

      <div style={{ background: '#fff', borderRadius: 16, border: `1px solid ${T.line}`,
        padding: '6px 18px', marginBottom: 18 }}>
        {rows.map((r, i) => (
          <div key={r.k} style={{
            display: 'flex', justifyContent: 'space-between', gap: 16,
            padding: '14px 0', borderBottom: i < rows.length - 1 ? `1px solid ${T.lineSoft}` : 'none',
            alignItems: 'flex-start' }}>
            <div style={{ fontFamily: T.sans, fontSize: 12.5, color: T.inkFaint, textTransform: 'uppercase',
              letterSpacing: 0.6, fontWeight: 500, flexShrink: 0, paddingTop: 2, width: 110 }}>{r.k}</div>
            <div style={{ fontFamily: T.sans, fontSize: 14.5, color: T.ink, textAlign: 'right',
              fontWeight: 450, lineHeight: 1.4, wordBreak: 'break-word' }}>{r.v}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', gap: 10 }}>
        <button onClick={onEdit}
          style={{ flex: 1, padding: '12px', background: 'transparent', color: T.forest,
            border: `1px solid ${T.forest}`, borderRadius: 999, fontFamily: T.sans, fontSize: 14,
            fontWeight: 500, cursor: 'pointer' }}>
          Change an answer
        </button>
        <button
          style={{ flex: 1.3, padding: '12px', background: T.forest, color: T.cream,
            border: 'none', borderRadius: 999, fontFamily: T.sans, fontSize: 14,
            fontWeight: 500, cursor: 'pointer' }}>
          All good — submit
        </button>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────
// Main — live AI chat loop
// ─────────────────────────────────────────────────────────────
function PortalChat({ lead = { firstName: 'Sarah', originalInquiry: 'a backyard remodel in Pleasanton' }, compact = false, useLiveAI = true }) {
  const [messages, setMessages] = useState([]);   // {role, text}
  const [stepIdx, setStepIdx] = useState(0);
  const [answers, setAnswers] = useState({});
  const [thinking, setThinking] = useState(true);
  const [showInput, setShowInput] = useState(false);
  const [done, setDone] = useState(false);
  const [routing, setRouting] = useState(null);
  const scrollRef = useRef(null);
  const lastUserMsgRef = useRef(null); // freeform user reply to feed back to LLM
  const initRef = useRef(false);

  // Scroll to bottom on update
  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages, showInput, thinking]);

  // Advance to next step
  const runStep = async (idx, prevUserMsg) => {
    if (idx >= SCRIPT.length) { finishFlow(); return; }
    const step = SCRIPT[idx];
    setThinking(true);
    setShowInput(false);

    let bubbles;
    if (useLiveAI && window.claude && window.claude.complete) {
      bubbles = await ivySay({ step, answers, userMessage: prevUserMsg, lead });
    } else {
      bubbles = fallbackFor(step, prevUserMsg);
    }

    // render bubbles one at a time with a pause so they pop in naturally
    for (let i = 0; i < bubbles.length; i++) {
      const b = bubbles[i];
      await new Promise(r => setTimeout(r, i === 0 ? 200 : 500));
      setMessages(m => [...m, { role: 'ai', text: b }]);
    }
    setThinking(false);
    setShowInput(true);
  };

  const finishFlow = async () => {
    setThinking(true);
    setShowInput(false);
    const r = computeRouting(answers);
    setRouting(r);
    let closing;
    if (useLiveAI && window.claude && window.claude.complete) {
      closing = await ivyClose({ answers, routing: r, lead });
    } else {
      closing = [`Perfect — you're all set. ${r.owner} will text you before calling.`];
    }
    for (const b of closing) {
      await new Promise(res => setTimeout(res, 400));
      setMessages(m => [...m, { role: 'ai', text: b }]);
    }
    setThinking(false);
    setTimeout(() => setDone(true), 1200);
  };

  // Kick off the first step once
  useEffect(() => {
    if (initRef.current) return;
    initRef.current = true;
    runStep(0, null);
  }, []);

  const commit = async (value) => {
    const step = SCRIPT[stepIdx];
    const display = typeof value === 'string' ? value
      : value.label || value.address
      || (value.files && value.skipped ? 'Skip' : value.files ? `${value.files.length} file${value.files.length === 1 ? '' : 's'}` : '')
      || JSON.stringify(value);
    // show the user's reply bubble
    setMessages(m => [...m, { role: 'user', text: display }]);
    // store answer synchronously for routing + AI context
    const newAnswers = { ...answers, [step.input.commitAs]: value };
    setAnswers(newAnswers);
    lastUserMsgRef.current = display;
    setShowInput(false);
    const next = stepIdx + 1;
    setStepIdx(next);
    // Let React flush, then ask Ivy for her next message
    setTimeout(() => runStep(next, display), 300);
  };

  if (done && routing) {
    return <SummaryScreen answers={answers} lead={lead} routing={routing} compact={compact}
      onEdit={() => { setDone(false); /* stay on last step — user can submit again */ }} />;
  }

  const step = SCRIPT[stepIdx];
  const input = step && step.input;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: T.cream }}>
      {/* header */}
      <div style={{
        padding: compact ? '12px 16px' : '14px 20px',
        borderBottom: `1px solid ${T.line}`, background: T.cream,
        display: 'flex', alignItems: 'center', gap: 12, flexShrink: 0 }}>
        <div style={{ width: 36, height: 36, borderRadius: 18, background: T.forest,
          display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <svg width="18" height="18" viewBox="0 0 18 18" fill={T.clay}>
            <path d="M9 2c-3 3-3 7 0 10 3-3 3-7 0-10zM3 10c1-1 3-1 4 0-1 1-3 1-4 0zm12 0c-1-1-3-1-4 0 1 1 3 1 4 0zM9 14v2"/>
          </svg>
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontFamily: T.sans, fontSize: 14, fontWeight: 500, color: T.ink, lineHeight: 1.1 }}>
            Ivy · Moss &amp; Stone
          </div>
          <div style={{ fontFamily: T.sans, fontSize: 11.5, color: T.ok, marginTop: 2,
            display: 'flex', alignItems: 'center', gap: 5 }}>
            <span style={{ width: 6, height: 6, borderRadius: 3, background: T.ok }}/>
            Project concierge
          </div>
        </div>
        <div style={{ fontFamily: T.mono, fontSize: 10, color: T.inkFaint, letterSpacing: 0.6,
          textTransform: 'uppercase' }}>
          {Math.min(stepIdx + 1, SCRIPT.length)} / {SCRIPT.length}
        </div>
      </div>

      {/* transcript */}
      <div ref={scrollRef} style={{ flex: 1, overflowY: 'auto', padding: '20px 16px 12px',
        background: T.cream, scrollBehavior: 'smooth' }}>
        {messages.map((m, i) => <Bubble key={i} role={m.role}>{m.text}</Bubble>)}
        {thinking && <TypingIndicator />}
      </div>

      {/* input */}
      {showInput && input && !thinking && (
        <div style={{ flexShrink: 0 }}>
          {input.kind === 'chips' && <Chips options={input.options} onPick={commit} />}
          {input.kind === 'text' && <TextInput placeholder={input.placeholder} onCommit={commit} autofocus={!compact} />}
          {input.kind === 'phone' && <TextInput placeholder="(555) 123-4567" kind="phone" onCommit={commit} />}
          {input.kind === 'budget' && <BudgetInput onCommit={commit} />}
          {input.kind === 'address' && <AddressInput onCommit={commit} />}
          {input.kind === 'upload' && <UploadInput onCommit={commit} />}
        </div>
      )}
    </div>
  );
}

Object.assign(window, { PortalChat, SummaryScreen, SCRIPT, computeRouting });
